from plexapi.server import PlexServer

from config import token, url

plex = PlexServer(url, token)

def get_movie_libraries():
#    plex_library_list = plex.library.sections()
    plex_movie_library_ids = [int(str(section).split(':')[1]) for section in plex.library.sections() if "MovieSection" in str(section)]
    return plex_movie_library_ids

def get_movies(library_id):
    movie_list = []
    print("Requesting movies from {}".format(library_id))
    working_library = plex.library.sectionByID(library_id)
    for video in working_library.search():
        movie_list.append(video)
    return movie_list

def get_movies_and_format():
    movies = []
    has_tag_counter = 0
    movie_counter = 0
    for library in get_movie_libraries():
        for movie in get_movies(library):
            if "Content Warnings:" in movie.summary:
                has_tag = "True"
                has_tag_counter += 1
            else:
                has_tag = "False"
            movies.append(dict(library=library, key=movie.key, title=movie.title, desc=movie.summary, has_tag = has_tag))
            movie_counter += 1
    print("Grabbed " + str(movie_counter) + " movies from Plex. " + str(has_tag_counter) + " of them already have content warnings.")
    return movies


def write_data(movie):
    # the value movie should be structured like one generated by build_json.py
    working_library = plex.library.sectionByID(movie['library'])
    desc_cut = movie['desc'].split("\r\n\r\nContent Warnings: \r\n\r\n")[0] #Removes Content Warnings if it is already there. Useful for ensuring there isn't duplication, and for update-all arg
    statuses = []
    if len(movie['statuses']) == 0:
        ddtd_status = "No content warnings could be retrieved for this film\nThis means either this film is fine, or it isn't present on DTDD"
    else:
        for status in movie['statuses']:
            if status[1] == "Yes":
                statuses.append(status[2])
        statuses.sort()
        ddtd_status = "This may contain: {}".format(', '.join(statuses))
    movie['desc'] = "{}\r\n\r\nContent Warnings: \r\n\r\n{}".format(desc_cut, ddtd_status)
    movie['id']=movie['key'].strip('/library/metadata/')
    working_movie = working_library.search(id=movie['id'])[0]
    try:
        working_movie.editSummary(movie['desc'])
    except:
        print("There was an error writing the movie description for Movie:" + movie['title'])

if __name__ == "__main__":
    # for testing only
    # show all movie libraries

    print("🎬 Film library IDs")
    for library in get_movie_libraries()[0]:
        print(library['key'])
